/********************************************************************************
* ServiceResolver.cs                                                            *
*                                                                               *
* Author: Denes Solti                                                           *
********************************************************************************/
using System;

namespace Solti.Utils.DI.Internals
{
    using Interfaces;

    /// <summary>
    /// Wrapper around the resolver function in order to let us store the related entry.
    /// </summary>
    /// <remarks>This is an internal class not meant for direct use.</remarks>
    public sealed record ServiceResolver(AbstractServiceEntry RelatedEntry, Func<IInstanceFactory, object> Resolve);  // Must be public in order to let us use in codes generated by CompiledCodeBTreeLookup
}
