#############################################################################
#                                                                           #
# appveyor.yml                                                              #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################

# common configuration for ALL branches
image: Visual Studio 2019

environment:
  COVERALLS_REPO_TOKEN:  
    secure: p2Kcud3WthUkXXcArmyAEggtW8E3L7ELxH0TXnjlnhmCUMPAQ9s5ApIX3By05W8B
  GITHUB_REPO_TOKEN:
    secure: qJEufJv866eebR/Boe1UnV3p1arOIX9BTyqAQnAVY49h4Ks40Sr0rHb3iN70e7BZ
  GITHUB_EMAIL:
    secure: Z6F+xZzdZzc5DMYB/4J0KUhyoTzTlXH75ciGl7hFH9s=

branches:
  # blacklist
  except:
    - gh-pages
 
# build on tags as well
skip_tags: false

build_script:
  # prevent MSBuild from running 
  - echo Starting build

before_test:
  - cmd: cd scripts

test_script:
  - cmd: test
  - cmd: coveralls.io

after_test:
  - cmd: cd ..
  # push test results  
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\BIN\testresults.xml))

# override settings for `master` branch and version tags
for:
-
  branches:
    only:
      # works with tag names: https://www.appveyor.com/docs/branches/#build-on-tags
      - /^perf$/

  test_script:
    # performance tests should run on "perf" tags only (time consuming)
    - cmd: perf
-
  branches:
    only:
      - master     
      - /^perf$/

  # update documentation
  deploy_script:
    - cmd: git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_REPO_TOKEN):x-oauth-basic@github.com`n"
    - cmd: git config --global user.email %GITHUB_EMAIL%
    - cmd: git config --global user.name "[Bot]"
    - cmd: cd scripts
    - cmd: gh-pages