#############################################################################
#                                                                           #
# appveyor.yml                                                              #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################

# common configuration for ALL branches
image: Visual Studio 2019

environment:
  COVERALLS_REPO_TOKEN:  
    secure: p2Kcud3WthUkXXcArmyAEggtW8E3L7ELxH0TXnjlnhmCUMPAQ9s5ApIX3By05W8B
  GITHUB_REPO_TOKEN:
    secure: qJEufJv866eebR/Boe1UnV3p1arOIX9BTyqAQnAVY49h4Ks40Sr0rHb3iN70e7BZ
  GITHUB_EMAIL:
    secure: Z6F+xZzdZzc5DMYB/4J0KUhyoTzTlXH75ciGl7hFH9s=

branches:
  # blacklist
  except:
    - gh-pages

# prevent MSBuild from running
build: off

before_test:
  - cmd: cd scripts

test_script:
  - cmd: echo running tests...

after_test:
  - cmd: uploadtestresults.appveyor

# override settings for `master` branch
for:
-
  branches:
    only:
      - master

  # update documentation
  deploy_script:
    - cmd: gitconfig.appveyor
    - cmd: gh-pages