image: Visual Studio 2017

skip_tags: true

install:
  - dotnet restore
  
build_script:
  - echo Starting build
 
test_script:
  - cover.cmd
  - perf.cmd
  
artifacts:
  - path: Coverage Report
    name: Coverage Report
    type: zip
    
  - path: BenchmarkDotNet.Artifacts
    name: BenchmarkDotNet.Artifacts
    type: zip  