#############################################################################
#                                                                           #
# appveyor.yml                                                              #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################

# common configuration for ALL branches
image: ubuntu

environment:
  COVERALLS_REPO_TOKEN:  
    secure: p2Kcud3WthUkXXcArmyAEggtW8E3L7ELxH0TXnjlnhmCUMPAQ9s5ApIX3By05W8B
  GITHUB_REPO_TOKEN:
    secure: qJEufJv866eebR/Boe1UnV3p1arOIX9BTyqAQnAVY49h4Ks40Sr0rHb3iN70e7BZ
  NUGET_REPO_TOKEN:
    secure: UlwkykISUtzAOpzVe0HdezbxNzE5UAXBpnMGu7rApIgjWbDG3ueXuFC92IOIpmtk
  GITHUB_EMAIL:
    secure: Z6F+xZzdZzc5DMYB/4J0KUhyoTzTlXH75ciGl7hFH9s=

branches:
  # blacklist
  except:
    - gh-pages

# prevent MSBuild from running
build: off

before_test:
  - ps: >-

      Set-Location -path "scripts"

      .(Join-Path "." "includes.ps1")

test_script:
  - ps: Test

after_test:
  - ps: Upload-Results

# override settings for `master` branch
for:
-
  branches:
    only:
      - master

  before_deploy:
    - ps: Git-Config
 
  deploy_script:
    # update documentation
    - ps: GH-Pages
    # publish nuget package
    - ps: Deploy